
pipeline{
    agent any

    environment{
         IMAGE_NAME = "tongsure/automate"
         IMAGE_TAG  = "lastest"
    }
    tools {
        git 'Default' // This ensures Jenkins uses the system-installed Git
    }
    stages{
        stage('Checkout Code'){
            steps{
                git branch: 'dev', url: 'https://github.com/Tongsure/test-jenkins.git'
            }
        }


        stage('Build Jar file'){
           steps{
              sh 'mvn clean package -DskipTests'
           }
        }

        stage('build docker Image'){
           steps{
               sh '''
                   docker build -t $IMAGE_NAME:$IMAGE_TAG .
               '''
           }
        }

//         stage('Push Image to Docker hub'){
//             steps{
//                withDockerRegistry([credentialsId : 'docker-hub-credentials' , url: 'https://index.docker.io/v1/']){
//                   sh '''
//                      docker push $IMAGE_NAME:$IMAGE_TAG
//                   '''
//                }
//             }
//          }
//
//         stage('Deploy to Kubernetes'){
//             steps{
//                sh '''
//                    kubectl apply -f k8s/deployment.yaml
//                '''
//
//             }
//
//         }

    }

    post {
        success {
            script {
                 MESSAGE = "Hello from Jenkins! Build Successful."
                sendMessage(MESSAGE)
            }
        }
        failure {
            script {
                 MESSAGE = "Jenkins Build Failed. Please check the logs!"
                 sendMessage(MESSAGE)
            }
        }
    }
}
def sendMessage(message) {
    def url = "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"
    def response = httpRequest(
        acceptType: 'APPLICATION_JSON',
        contentType: 'APPLICATION_JSON',
        httpMode: 'POST',
        url: "${url}?chat_id=${CHAT_ID}&text=${message}"
    )
    echo "Message sent to Telegram: ${response}"
}
